### ISSUE TITLE
Именование 

### ISSUE THREAD

**Issue by Frolikow** [OlyaSkoroded/slider.plugin#6]
![image](https://user-images.githubusercontent.com/25764783/66386689-d1a02d80-e9ec-11e9-8a50-88ac8aaa1a39.png)
странное решение писать словосочетания как одно слово. Нужно либо писать в camelCase, либо, что в данном случае лучше, писать kebab-case, т.е. через дефис. Для data-attributes то что надо.
___
что `subtype` можно понять из названия(подтип), но что такое `pubtype`(???). Нужно составные слова писать в camelCase. И избегать не явных сокращений
![image](https://user-images.githubusercontent.com/25764783/66387566-69eae200-e9ee-11e9-8abd-3d0310304549.png)

**Comment by Frolikow** [comment]
Не глядя на контекст - сразу ошибся со смыслом)
___
![image](https://user-images.githubusercontent.com/25764783/67072181-81745880-f1ae-11e9-86d5-f915e8965fb8.png)
здесь лучше слово "выравнивание" заменить на "ориентацию". Логичнее.
___
![image](https://user-images.githubusercontent.com/25764783/67072591-6a823600-f1af-11e9-84c1-25c6bece1c6b.png)
здесь во всем файле "настройки", а в методе "настройкА"
___
![image](https://user-images.githubusercontent.com/25764783/67072645-900f3f80-f1af-11e9-976b-502a5353edd1.png)
тут не явное именование. Это ведь элементы, а по имени - какбудто это метод)
___

**Comment by Frolikow** [comment]
Подумай как можно переименовать эти два элемента:
![image](https://user-images.githubusercontent.com/25764783/67280013-6ed38980-f4f6-11e9-9082-1c45e05f0a7a.png)
Если слайдер настроен на вертикальную ориентацию, то имена теряют свой смысл)

**Comment by OlyaSkoroded** [comment]
По поводу initSettingsTemplate. В коде слайдера, который у меня во втором проекте используется, увидела, что у автора разметка лежит в свойстве template, это мне логичным показалось, так у меня появилось settingTemplate, как бы шаблон настроек, а init, потому что я вроде что-то подготовила к использованию, определила значение, ну вот как то так цепочка сложилась)

**Comment by Frolikow** [comment]
> По поводу initSettingsTemplate. 

Как-то не не очень подходит на мой взгляд) `инициализацияШаблонаНастроек`, а в методе что происходит? инициализацию вижу, шаблона не вижу(по крайней мере точно не явно).

Во вьюхе слайдера у тебя логично выглядит имя с `template`, там есть реальная верстка) 
А здесь получается не к месту слово `шаблон`) Мб  стоит подумать о замене имени класса? у тебя сейчас называется `настройки`, я думаю что лучше будет `панель настроек` например) тогда и метод ты можешь назвать `инициализацияПанелиНастроек`) 
как считаешь?)

**Comment by Frolikow** [comment]
:+1: 
___
давай тут переименуем папку в style 
![image](https://user-images.githubusercontent.com/25764783/67635767-c14ce580-f8fc-11e9-9e66-6a6730fe596c.png)
___
тут лучше явно назвать $progressBar
![image](https://user-images.githubusercontent.com/25764783/67635832-4637ff00-f8fd-11e9-8e3d-3604938861c1.png)
___
Здесь на мой взгляд путаница:
![image](https://user-images.githubusercontent.com/25764783/67636372-851c8380-f902-11e9-95c0-39e985d96c74.png)
в атрибуте  `type` у тебя меняется формулировка все время, `options, newOptions, newState, newSettings`. По факту ведь одни и те же опции имеются ввиду? или нет? Поправь если я неправильно понял)
