### ISSUE TITLE
дублирование favicons

### ISSUE THREAD

**Issue by Frolikow** [OlyaSkoroded/slider.plugin#7]
Не понятно зачем  в конечной сборке тебе два комплекта иконок
![image](https://user-images.githubusercontent.com/25764783/66388153-b97ddd80-e9ef-11e9-8151-86f6744833ec.png)

**Comment by OlyaSkoroded** [comment]
Я туплю и не понимаю, что именно с иконками сделать)

**Comment by Frolikow** [comment]
у тебя сейчас папка dist, в которой сборка лежит, содержит фавиконы в двух экземплярах) один набор в `dist=>img=>favicons`. А второй в `dist=>src=>favicons`
